# Generated by Django 3.0 on 2021-09-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instuiteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetailes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
