# Generated by Django 3.0 on 2021-09-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instuiteapp', '0002_coursedetailes_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedetailes',
            old_name='image',
            new_name='profile_images',
        ),
    ]
