# Generated by Django 3.2.7 on 2021-09-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instuiteapp', '0003_auto_20210908_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetailes',
            name='profile_images',
        ),
        migrations.AddField(
            model_name='coursedetailes',
            name='profiles',
            field=models.ImageField(blank=True, default='profile_img/925667.jpg', null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='coursedetailes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
