# Generated by Django 3.2.7 on 2021-09-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instuiteapp', '0005_auto_20210910_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date_of_post',
        ),
        migrations.AlterField(
            model_name='contact',
            name='doute',
            field=models.CharField(choices=[('Englis', 'Ratnakumar'), ('python', 'Narayana'), ('ui', 'Python Narayan'), ('c', 'Jyothi'), ('django-doutes', 'DJANGO-ADI'), ('rest-api', 'Srinivas')], max_length=150),
        ),
    ]
