# Generated by Django 3.2.7 on 2021-09-09 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instuiteapp', '0006_auto_20210910_0046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
