# Generated by Django 3.2.7 on 2021-09-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instuiteapp', '0007_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.BigIntegerField()),
                ('enquiry_data', models.TextField()),
                ('doute', models.CharField(choices=[('c', 'Jyothi'), ('django-doutes', 'DJANGO-ADI'), ('python', 'Narayana'), ('Englis', 'Ratnakumar'), ('rest-api', 'Srinivas'), ('ui', 'Python Narayan')], max_length=150)),
                ('course', models.CharField(choices=[('5', 'django-doutes'), ('4', 'c'), ('2', 'ui'), ('6', 'English'), ('1', 'python'), ('3', 'rest-api')], max_length=120)),
                ('date_of_post', models.DateTimeField()),
            ],
        ),
    ]
