# Generated by Django 3.2.7 on 2021-09-09 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instuiteapp', '0008_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
