# Generated by Django 3.2.7 on 2021-09-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instuiteapp', '0009_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.BigIntegerField()),
                ('enquiry_data', models.TextField()),
                ('doute_triner', models.CharField(choices=[('django-doutes', 'DJANGO-ADI'), ('ui', 'Python Narayan'), ('c', 'Jyothi'), ('python', 'Narayana'), ('rest-api', 'Srinivas'), ('Englis', 'Ratnakumar')], max_length=150)),
                ('doute_course', models.CharField(choices=[('3', 'rest-api'), ('4', 'c'), ('1', 'python'), ('6', 'English'), ('2', 'ui'), ('5', 'django-doutes')], max_length=120)),
                ('date_of_post', models.DateTimeField()),
            ],
        ),
    ]
