# Generated by Django 3.2.7 on 2021-09-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instuiteapp', '0010_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='doute_course',
            field=models.CharField(choices=[('5', 'django-doutes'), ('4', 'c'), ('2', 'ui'), ('1', 'python'), ('3', 'rest-api'), ('6', 'English')], max_length=120),
        ),
        migrations.AlterField(
            model_name='contact',
            name='doute_triner',
            field=models.CharField(choices=[('python', 'Narayana'), ('rest-api', 'Srinivas'), ('Englis', 'Ratnakumar'), ('ui', 'Python Narayan'), ('django-doutes', 'DJANGO-ADI'), ('c', 'Jyothi')], max_length=150),
        ),
    ]
