# Generated by Django 3.2.7 on 2021-09-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instuiteapp', '0011_auto_20210911_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='doute_course',
            field=models.CharField(choices=[('3', 'rest-api'), ('5', 'django-doutes'), ('1', 'python'), ('4', 'c'), ('6', 'English'), ('2', 'ui')], max_length=120),
        ),
        migrations.AlterField(
            model_name='contact',
            name='doute_triner',
            field=models.CharField(choices=[('django-doutes', 'DJANGO-ADI'), ('python', 'Narayana'), ('Englis', 'Ratnakumar'), ('c', 'Jyothi'), ('ui', 'Python Narayan'), ('rest-api', 'Srinivas')], max_length=150),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(max_length=120),
        ),
    ]
