# Generated by Django 3.2.7 on 2021-09-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instuiteapp', '0012_auto_20210911_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='doute_course',
            field=models.CharField(choices=[('5', 'django-doutes'), ('4', 'c'), ('2', 'ui'), ('6', 'English'), ('1', 'python'), ('3', 'rest-api')], max_length=120),
        ),
        migrations.AlterField(
            model_name='contact',
            name='doute_triner',
            field=models.CharField(choices=[('django-doutes', 'DJANGO-ADI'), ('rest-api', 'Srinivas'), ('c', 'Jyothi'), ('python', 'Narayana'), ('ui', 'Python Narayan'), ('Englis', 'Ratnakumar')], max_length=150),
        ),
    ]
