# Generated by Django 3.2.7 on 2021-09-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instuiteapp', '0014_auto_20210911_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='doute_course',
            field=models.CharField(choices=[('1', 'python'), ('5', 'django-doutes'), ('2', 'ui'), ('6', 'English'), ('4', 'c'), ('3', 'rest-api')], max_length=120),
        ),
        migrations.AlterField(
            model_name='contact',
            name='doute_triner',
            field=models.CharField(choices=[('django-doutes', 'DJANGO-ADI'), ('ui', 'Python Narayan'), ('c', 'Jyothi'), ('Englis', 'Ratnakumar'), ('rest-api', 'Srinivas'), ('python', 'Narayana')], max_length=150),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
