# Generated by Django 3.2.7 on 2021-09-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instuiteapp', '0015_auto_20210911_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='message',
            new_name='mater',
        ),
        migrations.AlterField(
            model_name='contact',
            name='doute_course',
            field=models.CharField(choices=[('3', 'rest-api'), ('4', 'c'), ('2', 'ui'), ('6', 'English'), ('5', 'django-doutes'), ('1', 'python')], max_length=120),
        ),
        migrations.AlterField(
            model_name='contact',
            name='doute_triner',
            field=models.CharField(choices=[('ui', 'Python Narayan'), ('python', 'Narayana'), ('rest-api', 'Srinivas'), ('Englis', 'Ratnakumar'), ('c', 'Jyothi'), ('django-doutes', 'DJANGO-ADI')], max_length=150),
        ),
    ]
