# Generated by Django 3.2.7 on 2021-09-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instuiteapp', '0016_auto_20210911_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='doute_course',
            field=models.CharField(choices=[('1', 'python'), ('2', 'ui'), ('4', 'c'), ('3', 'rest-api'), ('5', 'django-doutes'), ('6', 'English')], max_length=120),
        ),
        migrations.AlterField(
            model_name='contact',
            name='doute_triner',
            field=models.CharField(choices=[('ui', 'Python Narayan'), ('Englis', 'Ratnakumar'), ('rest-api', 'Srinivas'), ('c', 'Jyothi'), ('django-doutes', 'DJANGO-ADI'), ('python', 'Narayana')], max_length=150),
        ),
    ]
