# Generated by Django 3.2.7 on 2021-09-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instuiteapp', '0017_auto_20210911_0926'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='EmailData',
        ),
        migrations.AlterField(
            model_name='contact',
            name='doute_course',
            field=models.CharField(choices=[('6', 'English'), ('5', 'django-doutes'), ('3', 'rest-api'), ('1', 'python'), ('2', 'ui'), ('4', 'c')], max_length=120),
        ),
        migrations.AlterField(
            model_name='contact',
            name='doute_triner',
            field=models.CharField(choices=[('python', 'Narayana'), ('rest-api', 'Srinivas'), ('Englis', 'Ratnakumar'), ('django-doutes', 'DJANGO-ADI'), ('c', 'Jyothi'), ('ui', 'Python Narayan')], max_length=150),
        ),
    ]
