# Generated by Django 3.2.7 on 2021-09-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instuiteapp', '0018_auto_20210911_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaildata',
            old_name='mater',
            new_name='msg',
        ),
        migrations.RenameField(
            model_name='emaildata',
            old_name='name',
            new_name='to',
        ),
        migrations.AlterField(
            model_name='contact',
            name='doute_course',
            field=models.CharField(choices=[('1', 'python'), ('6', 'English'), ('4', 'c'), ('3', 'rest-api'), ('5', 'django-doutes'), ('2', 'ui')], max_length=120),
        ),
        migrations.AlterField(
            model_name='contact',
            name='doute_triner',
            field=models.CharField(choices=[('python', 'Narayana'), ('ui', 'Python Narayan'), ('Englis', 'Ratnakumar'), ('django-doutes', 'DJANGO-ADI'), ('rest-api', 'Srinivas'), ('c', 'Jyothi')], max_length=150),
        ),
    ]
