# Generated by Django 3.2.7 on 2021-09-11 04:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Instuiteapp', '0019_auto_20210911_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaildata',
            name='email',
        ),
        migrations.AddField(
            model_name='emaildata',
            name='sub',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='doute_course',
            field=models.CharField(choices=[('4', 'c'), ('2', 'ui'), ('6', 'English'), ('1', 'python'), ('5', 'django-doutes'), ('3', 'rest-api')], max_length=120),
        ),
        migrations.AlterField(
            model_name='contact',
            name='doute_triner',
            field=models.CharField(choices=[('Englis', 'Ratnakumar'), ('ui', 'Python Narayan'), ('django-doutes', 'DJANGO-ADI'), ('python', 'Narayana'), ('c', 'Jyothi'), ('rest-api', 'Srinivas')], max_length=150),
        ),
        migrations.AlterField(
            model_name='emaildata',
            name='to',
            field=models.EmailField(max_length=254),
        ),
    ]
