# Generated by Django 3.2.7 on 2021-09-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instuiteapp', '0021_auto_20210911_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='doute_course',
            field=models.CharField(choices=[('5', 'django-doutes'), ('6', 'English'), ('2', 'ui'), ('3', 'rest-api'), ('4', 'c'), ('1', 'python')], max_length=120),
        ),
        migrations.AlterField(
            model_name='contact',
            name='doute_triner',
            field=models.CharField(choices=[('rest-api', 'Srinivas'), ('Englis', 'Ratnakumar'), ('c', 'Jyothi'), ('python', 'Narayana'), ('ui', 'Python Narayan'), ('django-doutes', 'DJANGO-ADI')], max_length=150),
        ),
        migrations.AlterField(
            model_name='emaildata',
            name='message',
            field=models.CharField(default='something', max_length=1000),
        ),
    ]
